### ISSUE TITLE
Add a simple Makefile please

### ISSUE THREAD

**Issue by MatthewHannigan** [naasking/async.h#1]
Hi,
A simple, useful Makefile could be a single line:

`main: example-buffer.o example-codelock.o example-small.o`

example

> ... async.h.git/async (master)$ **make**
> cc    -c -o example-buffer.o example-buffer.c
> cc    -c -o example-codelock.o example-codelock.c
> cc    -c -o example-small.o example-small.c
> cc     main.c example-buffer.o example-codelock.o example-small.o   -o main

**Comment by triwahyuu** [comment]
I have made a simple one in #4

**Comment by naasking** [comment]
Sorry for the delay, I haven't had a chance to boot into Linux and test it out. I will do so soon.

**Comment by triwahyuu** [comment]
any plan to make travis ci maybe?

**Comment by c-smile** [comment]
You can use premake5 file from my https://github.com/c-smile/async.hpp pretty much as it is.

Just change  `language "C++"` to `language "C"` and files from *.hpp, *.cpp to *.h and *.c

**Comment by naasking** [comment]
Pull request merged. Sorry for the delay!
