### ISSUE TITLE
enum ASYNC_EVT can be compiled to an 8-bit datatype

### ISSUE THREAD

**Issue by pcoutin** [naasking/async.h#3]
I was having problems using an async procedure with statements after line 127 with an ARM MCU. Was wondering why it would just stop working at some point, why the async function seemed to return -1 early. I noticed with the debugger that ASYNC_DONE had the value 0xff, I changed it from that to 0x7fffffff and now it works.

```C
typedef enum ASYNC_EVT { ASYNC_INIT = 0, ASYNC_DONE = 0x7fffffff } async;
```

**Comment by naasking** [comment]
Thanks, I've pushed a similar change closer to the intent I had. Let me know if you have any issues with the change.
